version: '2'
services:    
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"  
    volumes:
      - ./data/zookeeper/conf/zoo.cfg:/conf/zoo.cfg:Z
  zoonavigator_web:
    image: elkozmon/zoonavigator-web:latest
    container_name: zoonavigator-web
    ports:
     - "9091:8000"
    environment:
      API_HOST: "zoonavigator_api"
      API_PORT: 9000
    links:
     - zoonavigator_api
    depends_on:
     - zoonavigator_api
    restart: always
  zoonavigator_api:
    image: elkozmon/zoonavigator-api:latest
    container_name: zoonavigator-api
    environment:
      SERVER_HTTP_PORT: 9000
    restart: always
  kafka:
    image: bitnami/kafka:2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes 
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${HOSTNAME}:9092
    restart: always
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    restart: always
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"    
    volumes:
      - ./data/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z
    restart: always
  camunda:
    image: camunda/camunda-bpm-platform:latest
    container_name: camunda
    ports:
        - "9080:8080"
    restart: always
  component-dashboard:
    image: dfkibasys/component-dashboard:latest
    container_name: component-dashboard
    ports:
        - "9081:8080"
    environment:
      BASYS_REST_URL: http://localhost:8080
      MQTT_BROKER_IP: ${HOSTNAME}
      MQTT_BROKER_PORT: 9001
      CAMUNDA_REST_URL: http://${HOSTNAME}:9080
    restart: always
  process-dashboard:
    image: dfkibasys/process-dashboard:latest
    container_name: process-dashboard
    command: --camunda.rest.base.url=http://camunda:8080/engine-rest/engine/default
    ports:
        - "9082:8000"
    links:
        - camunda
    restart: always